### ISSUE TITLE
Strange behaviour on Windows blocks printing

### ISSUE THREAD

**Issue by johnscott4** [CartesianCo/argentum-control#45] opened 2014-12-19 04:23 UTC
In investigating why printing isn't working on Windows we discovered that there seems to be an issue with the first command invoked after reconnecting to the printer. For example, you have to invoke ls twice to get output. This, of course, drives the print logic mad.

**Comment by trent-waddington** [comment] 2014-12-27 02:10
I think this is mostly fixed now.. as for the cause, pySerial does strange stuff.

**Closed as completed by trent-waddington** 2014-12-27 02:10 UTC
